/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-12-18 02:38:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mysqlboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import boardmysql.*;
import java.text.SimpleDateFormat;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/color.jsp", Long.valueOf(1576547023352L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
 String bodyback_c="#e0ffff";
 String back_c="#8fbc8f";
 String title_c="#5f9ea0";
 String value_c="#b0e0e6";
 String bar="#778899";

      out.write('\r');
      out.write('\n');
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("   <link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write(" </head>\r\n");
      out.write(" \r\n");
      out.write(" ");

 int num=Integer.parseInt(request.getParameter("num"));
 String pageNum=request.getParameter("pageNum");
 SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
 
 BoardDAO dao=BoardDAO.getDao();//dao 객체 얻기 
 BoardDTO dto=dao.getArticle(num);//dao메서드 호출 
 
 int ref=dto.getRef();
 int re_step=dto.getRe_step();
 int re_level=dto.getRe_level();
 
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write("   <h1><center>글내용보기</center></h1>\r\n");
      out.write("   <table width=\"60%\" cellpadding=\"3\" align=\"center\">\r\n");
      out.write("   \r\n");
      out.write("     <tr height=\"30\">\r\n");
      out.write("       <td align=\"center\" width=\"125\" bgcolor=\"");
      out.print(value_c);
      out.write("\">글번호</td>\r\n");
      out.write("       <td align=\"center\" width=\"125\">");
      out.print(dto.getNum() );
      out.write("</td>\r\n");
      out.write("       \r\n");
      out.write("       <td align=\"center\" width=\"125\" bgcolor=\"");
      out.print(value_c);
      out.write("\">조횟수</td>\r\n");
      out.write("       <td align=\"center\" width=\"125\">");
      out.print(dto.getReadcount() );
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     \r\n");
      out.write("     <tr height=\"30\">\r\n");
      out.write("       <td align=\"center\" width=\"125\" bgcolor=\"");
      out.print(value_c);
      out.write("\">글쓴이</td>\r\n");
      out.write("       <td align=\"center\" width=\"125\">");
      out.print(dto.getWriter() );
      out.write("</td>\r\n");
      out.write("       \r\n");
      out.write("       <td align=\"center\" width=\"125\" bgcolor=\"");
      out.print(value_c);
      out.write("\">작성일</td>\r\n");
      out.write("       <td align=\"center\" width=\"125\">");
      out.print(dto.getReg_date() );
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("   \r\n");
      out.write("     <tr height=\"30\">\r\n");
      out.write("       <td align=\"center\" width=\"125\" bgcolor=\"");
      out.print(value_c);
      out.write("\">글제목</td>\r\n");
      out.write("       <td colspan=\"3\" align=\"center\" width=\"125\">");
      out.print(dto.getSubject() );
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     \r\n");
      out.write("     <tr height=\"30\">\r\n");
      out.write("       <td align=\"center\" width=\"125\" bgcolor=\"");
      out.print(value_c);
      out.write("\">글내용</td>\r\n");
      out.write("       <td colspan=\"3\" align=\"center\" width=\"125\" bgcolor=");
      out.print(value_c );
      out.write(">\r\n");
      out.write("       \r\n");
      out.write("       ");

	     String im = dto.getContent();
        im = im.replace("\n", "<br>");
       
      out.write("\r\n");
      out.write("        ");
      out.print(im );
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("      \r\n");
      out.write("     <tr height=\"30\">\r\n");
      out.write("       <td colspan=\"4\" bgcolor=\"");
      out.print(value_c);
      out.write("\" align=\"right\">\r\n");
      out.write("       <input type=\"button\" value=\"글수정\" onClick=\"document.location.href='updateForm.jsp?num=");
      out.print(dto.getNum());
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("'\">\r\n");
      out.write("       <input type=\"button\" value=\"글삭제\" onClick=\"document.location.href='deleteForm.jsp?num=");
      out.print(dto.getNum());
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("'\">\r\n");
      out.write("       <input type=\"button\" value=\"답글쓰기\" onClick=\"document.location.href='writeForm.jsp?num=");
      out.print(dto.getNum());
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("&ref=");
      out.print(ref);
      out.write("&re_step=");
      out.print(re_step);
      out.write("&re_level=");
      out.print(re_level);
      out.write("'\">\r\n");
      out.write("       <input type=\"button\" value=\"리스트\" onClick=\"document.location.href='list.jsp?pageNum=");
      out.print(pageNum);
      out.write("'\">\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("      \r\n");
      out.write("   </table>\r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
